Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          systemLogger:
            default:
              class: SJS\Hermod\Log\Backend\LokiBackend
              options:
                severityThreshold: "%LOG_DEBUG%"
                url: "%env:LOKI_URI%"
                user: "%env:LOKI_USER%"
                token: "%env:LOKI_TOKEN%"
                maxBufferSize: 150
                fallbackFile: "%FLOW_PATH_DATA%Logs/loki.log.jsonl"
                connectTimeout: 0.2
                readTimeout: 0.2
                labels:
                  target: systemLogger
          securityLogger:
            default:
              class: SJS\Hermod\Log\Backend\LokiBackend
              options:
                severityThreshold: "%LOG_DEBUG%"
                url: "%env:LOKI_URI%"
                user: "%env:LOKI_USER%"
                token: "%env:LOKI_TOKEN%"
                maxBufferSize: 150
                fallbackFile: "%FLOW_PATH_DATA%Logs/loki.log.jsonl"
                connectTimeout: 0.2
                readTimeout: 0.2
                labels:
                  target: securityLogger
        # sqlLogger:
        #   default:
        #     class: SJS\Hermod\Log\Backend\LokiBackend
        #     options:
        #       severityThreshold: "%LOG_INFO%"
        #       url: "%env:LOKI_URI%"
        #       user: "%env:LOKI_USER%"
        #       token: "%env:LOKI_TOKEN%"
        #       maxBufferSize: 150
        #       fallbackFile: "%FLOW_PATH_DATA%Logs/loki.log.jsonl"
        #       connectTimeout: 0.1
        #       readTimeout: 0.1
        #       labels:
        #         target: sqlLogger
        # i18nLogger:
        #   default:
        #     class: SJS\Hermod\Log\Backend\LokiBackend
        #     options:
        #       severityThreshold: "%LOG_INFO%"
        #       url: "%env:LOKI_URI%"
        #       user: "%env:LOKI_USER%"
        #       token: "%env:LOKI_TOKEN%"
        #       maxBufferSize: 150
        #       fallbackFile: "%FLOW_PATH_DATA%Logs/loki.log.jsonl"
        #       connectTimeout: 0.1
        #       readTimeout: 0.1
        #       labels:
        #         target: i18nLogger
