Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          systemLogger:
            default:
              class: SJS\Loki\Log\Backend\LokiBackend
              options:
                severityThreshold: "%LOG_DEBUG%"
                url: "%env:LOKI_URI%"
                user: "%env:LOKI_USER%"
                token: "%env:LOKI_TOKEN%"
                maxBufferSize: 150
                labels:
                  target: systemLogger
          securityLogger:
            default:
              class: SJS\Loki\Log\Backend\LokiBackend
              options:
                severityThreshold: "%LOG_DEBUG%"
                url: "%env:LOKI_URI%"
                user: "%env:LOKI_USER%"
                token: "%env:LOKI_TOKEN%"
                maxBufferSize: 1
                labels:
                  target: securityLogger
#         sqlLogger:
#           default:
#             class: SJS\Loki\Log\Backend\LokiBackend
#             options:
#               severityThreshold: "%LOG_INFO%"
#               url: "%env:LOKI_URI%"
#               user: "%env:LOKI_USER%"
#               token: "%env:LOKI_TOKEN%"
#               labels:
#                 target: sqlLogger

#         i18nLogger:
#           default:
#             class: SJS\Loki\Log\Backend\LokiBackend
#             options:
#               severityThreshold: "%LOG_INFO%"
#               url: "%env:LOKI_URI%"
#               user: "%env:LOKI_USER%"
#               token: "%env:LOKI_TOKEN%"
#               labels:
#                 target: i18nLogger
